notARepository: "skip"
promptToReturnFromSubprocess: false
startuppopupversion: 1

git:
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=format:"%C(auto)%h: %s (%C(blue)%an %C(white)| %C(cyan)%ad%C(white))" {{branchName}} --'
  paging:
    colorArg: always
    pager: delta --paging=never
  pull:
    mode: "rebase"

gui:
  showCommandLog: false
  showFileTree: true
  sidePanelWidth: 0.25
  skipstashwarning: true
  skipunstagelinewarning: false

keybinding:
  files:
    commitChanges: "C"
    commitChangesWithEditor: "c"
    toggleTreeView: "t"
  commits:
    renameCommit: "R"
    renameCommitWithEditor: "r"
