format = """
$directory\
$status\
$git_branch\
$git_state\
$git_status\
$fill \
$cmd_duration\
$time\
$line_break\
$jobs\
$sudo\
$character"""

[directory]
before_repo_root_style = "bright-white"
repo_root_style = "bold bright-white"
style = "bold bright-white"
truncate_to_repo = false

[status]
disabled = false
symbol = 'exit '

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\)'
style = "bright-black"

[git_status]
ahead = " ⇡"
behind = " ⇣"
deleted = " x"
diverged = " 🡙"
format = "[$conflicted]($style red)[$untracked$modified]($style yellow)[$staged]($style green)[$renamed$deleted]($style red)[$ahead_behind]($style blue) "
modified = " !"
renamed = " »"
staged = " +"
style = "bright-black"
untracked = " ?"

[fill]
style = '16'
symbol = '─'

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[time]
disabled = false
format = '[$time]($style) '
style = "bright-black"

[jobs]
format = '[$symbol$number]($style) '
style = "bold yellow"

[sudo]
disabled = false
format = '[𝐬]($style) '
style = 'bold yellow'

[character]
error_symbol = "[❰](red)"
success_symbol = "[❱](bright-white)"
vimcmd_symbol = "[❰](bright-white)"
