- defaults:
    link:
      relink: true
      create: true
      force: true
- clean:
    ~/:
      force: true
    ~/.config:
      force: true
      recursive: true
- create:
    ~/.config/fish:
- link:
    ~/:
      glob: true
      path: home/**
      prefix: "."
    /etc:
      glob: true
      path: etc/**
    ~/Library/LaunchAgents:
      glob: true
      path: launch-agents/**
    "~/Library/Keyboard Layouts/da-no-dead-keys.bundle":
      path: configs/da-no-dead-keys.bundle
