- defaults:
    link:
      relink: true
      create: true
      force: true
- clean:
    ~/:
      force: true
    ~/.config:
      force: true
      recursive: true
- create:
    ~/.config/fish:
- link:
    ~/:
      glob: true
      path: home/**
      prefix: "."
      exclude: [ home/config/nvim ]
    ~/.config/nvim:
      path: home/config/nvim
    /etc:
      glob: true
      path: etc/**
    ~/Library/LaunchAgents:
      glob: true
      path: launch-agents/**
