shell = "zsh"

[plugins.powerlevel10k]
github = 'romkatv/powerlevel10k'

[plugins.autoenv]
github = 'zpm-zsh/autoenv'

[plugins.fzf-tab]
github = 'aloxaf/fzf-tab'

[plugins.zsh-autosuggestions]
github = 'zsh-users/zsh-autosuggestions'

[plugins.zsh-completions]
github = 'zsh-users/zsh-completions'

[plugins.zsh-highlighting]
github = 'zsh-users/zsh-syntax-highlighting'

[plugins.zsh-abbr]
github = 'olets/zsh-abbr'

[plugins.zsh-npm-scripts-autocomplete]
github = 'grigorii-zander/zsh-npm-scripts-autocomplete'

[plugins.ugit]
github = 'bhupesh-v/ugit'

[plugins.ohmyzsh]
github = 'ohmyzsh/ohmyzsh'
dir = 'plugins'
use = ['{colored-man-pages,gnu-utils,ssh-agent}/*.plugin.zsh']
