# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json

notARepository: "skip"
promptToReturnFromSubprocess: false
disableStartupPopups: true

git:
  autoFetch: true
  branchLogCmd:
    'git log --graph --color=always --abbrev-commit --decorate --date=relative
    --pretty=format:"%C(auto)%h: %s (%C(blue)%an %C(white)|
    %C(cyan)%ad%C(white))" {{branchName}} --'
  log:
    showWholeGraph: false
  paging:
    colorArg: always
    pager: delta --paging=never

gui:
  animateExplosion: false
  expandFocusedSidePanel: true
  filterMode: fuzzy
  showCommandLog: false
  showFileTree: true
  showPanelJumps: false
  sidePanelWidth: 0.25
  skipRewordInEditorWarning: false
  skipStashWarning: true
  authorColors:
    "*": "blue"

keybinding:
  files:
    commitChanges: "C"
    commitChangesWithEditor: "c"
    toggleTreeView: "t"
  commits:
    renameCommit: "R"
    renameCommitWithEditor: "r"
